/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WasteRouteImport } from './routes/waste'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as IndexRouteImport } from './routes/index'

const WasteRoute = WasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/errors': typeof ErrorsRoute
  '/overview': typeof OverviewRoute
  '/patterns': typeof PatternsRoute
  '/sessions': typeof SessionsRoute
  '/tokens': typeof TokensRoute
  '/waste': typeof WasteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/errors': typeof ErrorsRoute
  '/overview': typeof OverviewRoute
  '/patterns': typeof PatternsRoute
  '/sessions': typeof SessionsRoute
  '/tokens': typeof TokensRoute
  '/waste': typeof WasteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/errors': typeof ErrorsRoute
  '/overview': typeof OverviewRoute
  '/patterns': typeof PatternsRoute
  '/sessions': typeof SessionsRoute
  '/tokens': typeof TokensRoute
  '/waste': typeof WasteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/costs'
    | '/errors'
    | '/overview'
    | '/patterns'
    | '/sessions'
    | '/tokens'
    | '/waste'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/costs'
    | '/errors'
    | '/overview'
    | '/patterns'
    | '/sessions'
    | '/tokens'
    | '/waste'
  id:
    | '__root__'
    | '/'
    | '/costs'
    | '/errors'
    | '/overview'
    | '/patterns'
    | '/sessions'
    | '/tokens'
    | '/waste'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CostsRoute: typeof CostsRoute
  ErrorsRoute: typeof ErrorsRoute
  OverviewRoute: typeof OverviewRoute
  PatternsRoute: typeof PatternsRoute
  SessionsRoute: typeof SessionsRoute
  TokensRoute: typeof TokensRoute
  WasteRoute: typeof WasteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waste': {
      id: '/waste'
      path: '/waste'
      fullPath: '/waste'
      preLoaderRoute: typeof WasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CostsRoute: CostsRoute,
  ErrorsRoute: ErrorsRoute,
  OverviewRoute: OverviewRoute,
  PatternsRoute: PatternsRoute,
  SessionsRoute: SessionsRoute,
  TokensRoute: TokensRoute,
  WasteRoute: WasteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
